var files_dup =
[
    [ "anyfloat.hpp", "anyfloat_8hpp_source.html", null ],
    [ "bf16.h", "bf16_8h_source.html", null ],
    [ "bithippop.hpp", "bithippop_8hpp_source.html", null ],
    [ "conf.py", "conf_8py_source.html", null ],
    [ "cposit.h", "cposit_8h_source.html", null ],
    [ "fixedtraits.hpp", "fixedtraits_8hpp_source.html", null ],
    [ "float16native32.hpp", "float16native32_8hpp_source.html", null ],
    [ "floatconst2bits.hpp", "floatconst2bits_8hpp_source.html", null ],
    [ "floattraits.hpp", "floattraits_8hpp_source.html", null ],
    [ "logger.hpp", "logger_8hpp_source.html", null ],
    [ "interface/cereal/posit.h", "interface_2cereal_2posit_8h_source.html", null ],
    [ "posit.h", "posit_8h_source.html", null ],
    [ "posit10.hpp", "posit10_8hpp_source.html", null ],
    [ "posit12.hpp", "posit12_8hpp_source.html", null ],
    [ "posit14.hpp", "posit14_8hpp_source.html", null ],
    [ "posit8.hpp", "posit8_8hpp_source.html", null ],
    [ "posit_logtab.hpp", "posit__logtab_8hpp_source.html", null ],
    [ "posit_tab.hpp", "posit__tab_8hpp_source.html", null ],
    [ "positeigen.h", "positeigen_8h_source.html", null ],
    [ "softback.hpp", "softback_8hpp_source.html", null ],
    [ "softfloat.hpp", "softfloat_8hpp_source.html", null ],
    [ "typehelpers.hpp", "typehelpers_8hpp_source.html", null ]
];