var hierarchy =
[
    [ "any_floattrait< exp_bits, frac_bits, value_T, holder_T, with_denorm_ >", "structany__floattrait.html", null ],
    [ "anyfloat_emu< expbits, fractionbits, value_t, holder_t, impl_t, with_denorm_ >", "classanyfloat__emu.html", null ],
    [ "posit::BackendFixed< FT, ET >", "structposit_1_1_backend_fixed.html", null ],
    [ "posit::BackendFloat< B >", "structposit_1_1_backend_float.html", null ],
    [ "bitset_leftmost_get_const< T, N >", "structbitset__leftmost__get__const.html", null ],
    [ "bitset_leftmost_get_const< T, 0 >", "structbitset__leftmost__get__const_3_01_t_00_010_01_4.html", null ],
    [ "cast_msb_< A, abits, B, bbits, abits_gt_bbits >", "structcast__msb__.html", null ],
    [ "cast_msb_< A, abits, B, bbits, false >", "structcast__msb___3_01_a_00_01abits_00_01_b_00_01bbits_00_01false_01_4.html", null ],
    [ "cast_msb_< A, abits, B, bbits, true >", "structcast__msb___3_01_a_00_01abits_00_01_b_00_01bbits_00_01true_01_4.html", null ],
    [ "cast_msb_< A, abits, B, bbits,(abits > bbits)>", null, [
      [ "cast_msb< A, abits, B, bbits >", "structcast__msb.html", null ]
    ] ],
    [ "cast_right_to_left_< A, abits, B, bbits, abits_gt_bbits >", "structcast__right__to__left__.html", null ],
    [ "cast_right_to_left_< A, abits, B, bbits, false >", "structcast__right__to__left___3_01_a_00_01abits_00_01_b_00_01bbits_00_01false_01_4.html", null ],
    [ "cast_right_to_left_< A, abits, B, bbits, true >", "structcast__right__to__left___3_01_a_00_01abits_00_01_b_00_01bbits_00_01true_01_4.html", null ],
    [ "cast_right_to_left_< A, abits, B, bbits,(abits > bbits)>", null, [
      [ "cast_right_to_left< A, abits, B, bbits >", "structcast__right__to__left.html", null ]
    ] ],
    [ "anyfloat_emu< expbits, fractionbits, value_t, holder_t, impl_t, with_denorm_ >::DeepInit", "structanyfloat__emu_1_1_deep_init.html", null ],
    [ "DeepInit", "struct_deep_init.html", null ],
    [ "posit::Posit< T, totalbits, esbits, FT, positspec >::DeepInit", "structposit_1_1_posit_1_1_deep_init.html", null ],
    [ "posit_logtab< T, totalbits, esbits, FFT >::DeepInit", "structposit__logtab_1_1_deep_init.html", null ],
    [ "double_trait", "structdouble__trait.html", null ],
    [ "double_union", "uniondouble__union.html", null ],
    [ "nextinttype< T >::error_type_is_too_large_or_missing_128bit_integer", "structnextinttype_1_1error__type__is__too__large__or__missing__128bit__integer.html", null ],
    [ "std::false_type", null, [
      [ "posit::is_posit_backend< T >", "structposit_1_1is__posit__backend.html", null ],
      [ "std::is_unsigned< signed128 >", "classstd_1_1is__unsigned_3_01signed128_01_4.html", null ]
    ] ],
    [ "fixedtrait< T, N, F >", "structfixedtrait.html", null ],
    [ "float16n32", "structfloat16n32.html", null ],
    [ "float2trait< T >", "structfloat2trait.html", null ],
    [ "float2trait< double >", "structfloat2trait_3_01double_01_4.html", null ],
    [ "float2trait< float >", "structfloat2trait_3_01float_01_4.html", null ],
    [ "float2trait< halffloat >", "structfloat2trait_3_01halffloat_01_4.html", null ],
    [ "float2trait< halffloatalt >", "structfloat2trait_3_01halffloatalt_01_4.html", null ],
    [ "float_union", "unionfloat__union.html", null ],
    [ "posit::fraction_bit_extract< abits, AT, bbits, BT, abits_gt_bbits, msb >", "structposit_1_1fraction__bit__extract.html", null ],
    [ "posit::fraction_bit_extract< abits, AT, bbits, BT, false, msb >", "structposit_1_1fraction__bit__extract_3_01abits_00_01_a_t_00_01bbits_00_01_b_t_00_01false_00_01msb_01_4.html", null ],
    [ "posit::fraction_bit_extract< abits, AT, bbits, BT, true, msb >", "structposit_1_1fraction__bit__extract_3_01abits_00_01_a_t_00_01bbits_00_01_b_t_00_01true_00_01msb_01_4.html", null ],
    [ "anyfloat_emu< expbits, fractionbits, value_t, holder_t, impl_t, with_denorm_ >::FullWriter", "structanyfloat__emu_1_1_full_writer.html", null ],
    [ "GenericNumTraits", null, [
      [ "Eigen::NumTraits< Posit< T, totalbits, esbits, FT, positspec > >", "struct_eigen_1_1_num_traits_3_01_posit_3_01_t_00_01totalbits_00_01esbits_00_01_f_t_00_01positspec_01_4_01_4.html", null ],
      [ "Eigen::NumTraits< Unpacked< FT, ET > >", "struct_eigen_1_1_num_traits_3_01_unpacked_3_01_f_t_00_01_e_t_01_4_01_4.html", null ]
    ] ],
    [ "half_trait", "structhalf__trait.html", null ],
    [ "std::hash< posit::Posit< B, totalbits, esbits, FT, positspec > >", "structstd_1_1hash_3_01posit_1_1_posit_3_01_b_00_01totalbits_00_01esbits_00_01_f_t_00_01positspec_01_4_01_4.html", null ],
    [ "detail_least::int_least_helper< Category >", "structdetail__least_1_1int__least__helper.html", null ],
    [ "detail_least::int_least_helper< 1 >", "structdetail__least_1_1int__least__helper_3_011_01_4.html", null ],
    [ "detail_least::int_least_helper< 2 >", "structdetail__least_1_1int__least__helper_3_012_01_4.html", null ],
    [ "detail_least::int_least_helper< 3 >", "structdetail__least_1_1int__least__helper_3_013_01_4.html", null ],
    [ "detail_least::int_least_helper< 4 >", "structdetail__least_1_1int__least__helper_3_014_01_4.html", null ],
    [ "detail_least::int_least_helper< 5 >", "structdetail__least_1_1int__least__helper_3_015_01_4.html", null ],
    [ "detail_least::int_least_helper<((N)<=8)+((N)<=16)+((N)<=32)+((N)<=64)+((N)<=128)>", null, [
      [ "int_least_bits< N >", "structint__least__bits.html", null ]
    ] ],
    [ "posit::lightfixed< ET, FT, FXT >", "structposit_1_1lightfixed.html", null ],
    [ "Logger< T >", "class_logger.html", null ],
    [ "msb_exp< T, hbits, ebits, zeroes >", "structmsb__exp.html", null ],
    [ "msb_exp< T, hbits, ebits, false >", "structmsb__exp_3_01_t_00_01hbits_00_01ebits_00_01false_01_4.html", null ],
    [ "msb_exp< T, hbits, ebits, true >", "structmsb__exp_3_01_t_00_01hbits_00_01ebits_00_01true_01_4.html", null ],
    [ "nextintop< T >", "structnextintop.html", null ],
    [ "nextinttype< T >", "structnextinttype.html", null ],
    [ "nextinttype< int16_t >", "structnextinttype_3_01int16__t_01_4.html", null ],
    [ "nextinttype< int32_t >", "structnextinttype_3_01int32__t_01_4.html", null ],
    [ "nextinttype< int8_t >", "structnextinttype_3_01int8__t_01_4.html", null ],
    [ "nextinttype< uint16_t >", "structnextinttype_3_01uint16__t_01_4.html", null ],
    [ "nextinttype< uint32_t >", "structnextinttype_3_01uint32__t_01_4.html", null ],
    [ "nextinttype< uint64_t >", "structnextinttype_3_01uint64__t_01_4.html", null ],
    [ "nextinttype< uint8_t >", "structnextinttype_3_01uint8__t_01_4.html", null ],
    [ "std::numeric_limits< class posit_logtab< T, totalbits, esbits, FFT > >", "classstd_1_1numeric__limits_3_01class_01posit__logtab_3_01_t_00_01totalbits_00_01esbits_00_01_f_f_t_01_4_01_4.html", null ],
    [ "std::numeric_limits< posit::Posit< B, totalbits, esbits, FT, positspec > >", "classstd_1_1numeric__limits_3_01posit_1_1_posit_3_01_b_00_01totalbits_00_01esbits_00_01_f_t_00_01positspec_01_4_01_4.html", null ],
    [ "std::numeric_limits< softfloat32 >", "structstd_1_1numeric__limits_3_01softfloat32_01_4.html", null ],
    [ "posit::Posit< T, totalbits, esbits, FT, positspec >", "classposit_1_1_posit.html", null ],
    [ "posit_logtab< T, totalbits, esbits, FFT >", "classposit__logtab.html", null ],
    [ "posit_logtab_helper< T, totalbits, esbits, FFT, positspec >", "structposit__logtab__helper.html", null ],
    [ "posit::PositPacker< PT, Target >", "structposit_1_1_posit_packer.html", null ],
    [ "posit::PositPacker< PT, BackendFixed< FT, typename PT::exponenttype > >", "structposit_1_1_posit_packer_3_01_p_t_00_01_backend_fixed_3_01_f_t_00_01typename_01_p_t_1_1exponenttype_01_4_01_4.html", null ],
    [ "posit::PositPacker< PT, BackendFloat< FT > >", "structposit_1_1_posit_packer_3_01_p_t_00_01_backend_float_3_01_f_t_01_4_01_4.html", null ],
    [ "posit::PositPacker< PT, Unpacked< FT, typename PT::exponenttype > >", "structposit_1_1_posit_packer_3_01_p_t_00_01_unpacked_3_01_f_t_00_01typename_01_p_t_1_1exponenttype_01_4_01_4.html", null ],
    [ "posit::PositSpecTrait< x >", "structposit_1_1_posit_spec_trait.html", null ],
    [ "posit::PositSpecTrait< WithInfs >", "structposit_1_1_posit_spec_trait_3_01_with_infs_01_4.html", null ],
    [ "posit::PositSpecTrait< WithNan >", "structposit_1_1_posit_spec_trait_3_01_with_nan_01_4.html", null ],
    [ "posit::PositSpecTrait< WithNanInfs >", "structposit_1_1_posit_spec_trait_3_01_with_nan_infs_01_4.html", null ],
    [ "posit::PositSpecTrait< WithNone >", "structposit_1_1_posit_spec_trait_3_01_with_none_01_4.html", null ],
    [ "posit::PositTrait< T, totalbits, esbits, positspec_ >", "structposit_1_1_posit_trait.html", null ],
    [ "posit::PositZero< x >", "structposit_1_1_posit_zero.html", null ],
    [ "posit::PositZero< 0 >", "structposit_1_1_posit_zero_3_010_01_4.html", null ],
    [ "posit::PositZero< 1 >", "structposit_1_1_posit_zero_3_011_01_4.html", null ],
    [ "printableinttype< T >", "structprintableinttype.html", null ],
    [ "printableinttype< const T >", "structprintableinttype_3_01const_01_t_01_4.html", null ],
    [ "printableinttype< int8_t >", "structprintableinttype_3_01int8__t_01_4.html", null ],
    [ "printableinttype< uint8_t >", "structprintableinttype_3_01uint8__t_01_4.html", null ],
    [ "posit::BackendFixed< FT, ET >::raw_tag", "structposit_1_1_backend_fixed_1_1raw__tag.html", null ],
    [ "signed128", "structsigned128.html", null ],
    [ "posit::BackendFixed< FT, ET >::single_tag", "structposit_1_1_backend_fixed_1_1single__tag.html", null ],
    [ "posit::BackendFloat< B >::single_tag", "structposit_1_1_backend_float_1_1single__tag.html", null ],
    [ "posit::Unpacked< FT, ET >::single_tag", "structposit_1_1_unpacked_1_1single__tag.html", null ],
    [ "single_trait", "structsingle__trait.html", null ],
    [ "softfloat16", "structsoftfloat16.html", null ],
    [ "softfloat32", "structsoftfloat32.html", null ],
    [ "std::true_type", null, [
      [ "posit::is_posit_backend< BackendFixed< B, ET > >", "structposit_1_1is__posit__backend_3_01_backend_fixed_3_01_b_00_01_e_t_01_4_01_4.html", null ],
      [ "posit::is_posit_backend< BackendFloat< B > >", "structposit_1_1is__posit__backend_3_01_backend_float_3_01_b_01_4_01_4.html", null ],
      [ "posit::is_posit_backend< Unpacked< FT, ET > >", "structposit_1_1is__posit__backend_3_01_unpacked_3_01_f_t_00_01_e_t_01_4_01_4.html", null ],
      [ "std::is_unsigned< unsigned128 >", "classstd_1_1is__unsigned_3_01unsigned128_01_4.html", null ]
    ] ],
    [ "posit::Unpacked< FT, ET >", "structposit_1_1_unpacked.html", null ],
    [ "posit::UnpackedPosit< PT >", "structposit_1_1_unpacked_posit.html", null ],
    [ "unsigned128", "structunsigned128.html", null ],
    [ "valuewrap< T >", "structvaluewrap.html", null ],
    [ "valuewrap< uint16_t >", "structvaluewrap.html", [
      [ "halffloat", "structhalffloat.html", null ],
      [ "halffloatalt", "structhalffloatalt.html", null ]
    ] ],
    [ "valuewrap< uint32_t >", "structvaluewrap.html", [
      [ "singlefloat", "structsinglefloat.html", null ]
    ] ],
    [ "valuewrap< uint8_t >", "structvaluewrap.html", [
      [ "microfloat", "structmicrofloat.html", null ]
    ] ]
];