# This is a basic workflow to help you get started with Actions

name: autodoc

on: [push]

jobs:
  build:
    name: Push Sphinx Pages
    runs-on: ubuntu-latest
    steps:
    - uses: seanzhengw/sphinx-pages@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_readme: true
